# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - name: Commit files
      run: |
        cd ./.vuepress/dist
        git init
        git config --global user.email young20050727@gmail.com
        git config --global user.name Young-TW
        git status
        git remote add origin https://${{secrets.COMMIT_SECRET}}@github.com/Young-TW/note.git
        git checkout -b gh-pages-1
        git add --all
        git commit -m "update"
        git push origin gh-pages-1 -f